services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: vetconnect
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: suasenha
    ports:
      - "5432:5432"
    volumes:
      - ./banco:/docker-entrypoint-initdb.d

  backend:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./backend:/app
    command: sh -c "npm install && node server.js"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: suasenha
      DB_NAME: vetconnect
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - db